### PR TITLE
Adding 1.3.1.1-oci release

### PR DESCRIPTION
**Pull request by zoxpx**
Adding catalog entry for 1.3.1.1 OCI release

### CODE REVIEW

**Comment by zoxpx** [comment]
NOTE, this PR depends on https://github.com/portworx/rancher-catalog/pull/8 (introduced ver 7) - as it uses version number 8

**Comment by sensri108** [comment]
can you please resolve the branch conflicts? thanks

**Comment by zoxpx** [comment]
fixed.

**Review by sensri108 — COMMENTED** [review]
reviewed

**Pull request merged**
