### PR TITLE
Adding Portworx v1.4.2.2 entry

### PR DESCRIPTION
**Pull request by zoxpx**

### CODE REVIEW

**Comment by sensri108** [comment]
Catalog failing to deploy the portworx and found below error message. 

sudo journalctl -lfu portworx
-- Logs begin at Sat 2018-04-21 15:23:04 UTC. --
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=info msg="Starting REST service on socket : /var/lib/osd/driver/pxd.sock"
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=info msg="PX is ready on Node: node3. CLI accessible at /opt/pwx/bin/pxctl."
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=info msg="Detected node node1  to be in the cluster."
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=info msg="Detected node node2  to be in the cluster."
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=info msg="Forcing the rescan of Docker drivers"
Aug 16 20:34:16 node3 px-runc[8026]: time="2018-08-16T20:34:16Z" level=warning msg="404   Failed to locate volume: Cannot locate volume with name portworx-bootup-dummy-volume-check-please-ignore" Driver=pxd ID=portworx-bootup-dummy-volume-check-please-ignore Request=get
Aug 16 20:34:53 node3 px-runc[8026]: 2018-08-16 20:34:53,400 INFO reaped unknown pid 6883
Aug 16 20:59:14 node3 px-runc[8026]: time="2018-08-16T20:59:14Z" level=warning msg="404   Failed to locate volume: Cannot locate volume with name rancher-cni" Driver=pxd ID=rancher-cni Request=get
Aug 16 20:59:14 node3 px-runc[8026]: time="2018-08-16T20:59:14Z" level=warning msg="404   Failed to locate volume: Cannot locate volume with name rancher-agent-state" Driver=pxd ID=rancher-agent-state Request=get
Aug 16 21:01:16 node3 px-runc[8026]: time="2018-08-16T21:01:16Z" level=warning msg="404   Failed to locate volume: Cannot locate volume with name rancher-cni-driver" Driver=pxd ID=rancher-cni-driver Request=get
Aug 16 21:49:20 node3 px-runc[8026]: time="2018-08-16T21:49:20Z" level=warning msg="No gossip update for  59.544172982 s"
Aug 16 21:49:20 node3 px-runc[8026]: 2018/08/16 21:49:20 [WARN] memberlist 192.168.56.63: Suspect message from node2v2
Aug 16 21:49:21 node3 px-runc[8026]: 2018/08/16 21:49:21 [INFO] memberlist: Suspect node2v2 has failed, no acks received
Aug 16 21:49:21 node3 px-runc[8026]: 2018/08/16 21:49:21 [WARN] memberlist 192.168.56.63: Suspect message from node3v2

**Comment by sensri108** [comment]
Reevaluating the same in different rancher catalog

**Comment by zoxpx** [comment]
Make sure your firewall is off, and PX-nodes are time-synchronized (ie. NTP service on).

**Comment by sensri108** [comment]
Validated successfully.

**Pull request merged**
